services:
  - type: web
    name: tienda-nj-backend
    env: node
    plan: starter
    buildCommand: chmod +x install-chrome.sh && ./install-chrome.sh && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/.cache/puppeteer
      - key: CHROME_BIN
        value: /opt/render/project/src/.cache/puppeteer/chrome-linux/chrome
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - nest-cli.json
        - install-chrome.sh 