services:
  - type: web
    name: tienda-nj-backend
    env: node
    plan: starter
    buildCommand: npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - nest-cli.json 