services:
  - type: web
    name: tienda-nj-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: CHROME_BIN
        value: /opt/render/project/src/node_modules/puppeteer/.local-chromium/linux-*/chrome-linux/chrome
    buildFilter:
      paths:
        - src/**
        - package.json
        - package-lock.json
        - tsconfig.json
        - nest-cli.json 