export const SERVER_PORT='SERVER_PORT'
export const DB_HOTS= 'DB_HOTS'
export const DB_PORT= 'DB_PORT'
export const DB_PASSWORD= 'DB_PASSWORD'
export const DB_USER= 'DB_USER'
export const DB_NAME= 'DB_NAME'
export const JWT_SECRET= 'JWT_SECRET'